server:
  port: 8845
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  boot:
    admin:
      discovery:
        enabled: true
      ui:
        title: Sanzee Cloud Dash Board