#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888 # URL of the Config Server
#      profile: dev               # Environment profile (e.g., dev, prod, staging)
##      label: main                # Optional: Branch or label in the Config Server's Git repository

server:
  port: 8847
spring:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:21811,127.0.0.1:21812,127.0.0.1:21813
  discovery:
    enabled: true