server:
  port: 8847
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - StripPrefix=1
    loadbalancer:
      retry:
        enabled: true
      nacos:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
sanzee-cloud:
  gateway:
    whiteList:
      - "/oauth2/**"
      - "/v3/api-docs/**"
      - "/openapi*"
      - "/open/**"
springdoc:
  api-docs:
    enabled: true