spring:
  application:
#    name: @artifactId@  #Get value in POM file
    name: sanzee-cloud-gateway  #Get value in POM file
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
