spring:
  cloud:
    config:
      uri: http://127.0.0.1:8888 # URL of the Config Server
      profile: prod               # Environment profile (e.g., dev, prod, staging)
#      label: main                # Optional: Branch or label in the Config Server's Git repository